from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Protocol

class ChatSession(Protocol):
    def send_message(self, content: str) -> Any: ...

class GenerativeModel:
    def __init__(self, *, model_name: str, system_instruction: str) -> None: ...
    def start_chat(self, history: Iterable[Any] | None = ...) -> ChatSession: ...
    def generate_content(self, content: str) -> Any: ...

def configure(*, api_key: str) -> None: ...
