name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install runtime dependencies
        run: pip install -r requirements.txt
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Lint
        run: ruff check fred_zulip_bot tests
      - name: Format check
        run: ruff format --check fred_zulip_bot tests
      - name: Type check
        run: mypy fred_zulip_bot
      - name: Security scan
        run: bandit -q -r fred_zulip_bot
      - name: Dependency audit
        run: pip-audit --ignore-vuln GHSA-f96h-pmfr-66vw --ignore-vuln GHSA-2c2j-9gv5-cj73 --ignore-vuln GHSA-4xh5-x5gv-qwph
      - name: Test
        run: pytest
